// <auto-generated />
using System;
using GameForum.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GameForum.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameForum.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cassification")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Classificacao_Do_Jogo");

                    b.Property<int>("JogoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_Da_Postagem");

                    b.Property<string>("TxtAvaliation")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Conteudo_Da_Avaliacao");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UserId");

                    b.ToTable("Tabela_Avalicao");
                });

            modelBuilder.Entity("GameForum.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_do_Comentario");

                    b.Property<int>("JogoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TxtComment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Texto_Do_Comentario");

                    b.Property<int>("UseId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("AvaliationId");

                    b.HasIndex("JogoId");

                    b.HasIndex("UseId");

                    b.ToTable("Tabela_De_Comentarios");
                });

            modelBuilder.Entity("GameForum.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Desenvolvedora_Do_Jogo");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Genero_Do_Jogo");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Plataforma_Do_Jogo");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_De_Publicação");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Titulo_Do_Jogo");

                    b.HasKey("Id");

                    b.ToTable("Tabela_Jogo");
                });

            modelBuilder.Entity("GameForum.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_do_registro");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Foto_De_Perfil");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("Usuario_Ativo");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nick");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Hash_da_senha");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nome_De_Usuario");

                    b.HasKey("Id");

                    b.ToTable("Tabela_Usuarios");
                });

            modelBuilder.Entity("GameForum.Models.Avaliacao", b =>
                {
                    b.HasOne("GameForum.Models.Jogo", "Jogo")
                        .WithMany("Avaliations")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameForum.Models.Usuario", "Usuario")
                        .WithMany("Avaliations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameForum.Models.Comentario", b =>
                {
                    b.HasOne("GameForum.Models.Avaliacao", "Avaliacao")
                        .WithMany("Comentarios")
                        .HasForeignKey("AvaliationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameForum.Models.Jogo", "Jogo")
                        .WithMany("comentarios")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameForum.Models.Usuario", "Usuario")
                        .WithMany("comentarios")
                        .HasForeignKey("UseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameForum.Models.Avaliacao", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("GameForum.Models.Jogo", b =>
                {
                    b.Navigation("Avaliations");

                    b.Navigation("comentarios");
                });

            modelBuilder.Entity("GameForum.Models.Usuario", b =>
                {
                    b.Navigation("Avaliations");

                    b.Navigation("comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
